name: Run github_pipeline pipeline from github_pipeline.py
'on':
  schedule:
  - cron: 0 */6 * * *
  workflow_dispatch: null
env:
  OWNER: ${{ secrets.OWNER }} }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.14.x
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run pipeline script
      run: python 'github_pipeline.py'
